[build]
builder = "HEROKU"
buildCommand = "./gradlew clean build -x check -x test -Pproduction"

[deploy]
startCommand = "java -Xmx512m -Xms256m -XX:MaxMetaspaceSize=128m -Dserver.port=$PORT -jar build/libs/*-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3