[build]
builder = "NIXPACKS"

[build.nixpacks]
version = "1.21.0"

[build.nixpacksPlan.setup]
nixPkgs = ["...", "jdk21"]

[env]
NIXPACKS_JDK_VERSION = "21"
JAVA_VERSION = "21"

[deploy]
startCommand = "java -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/*-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3